apiVersion: apps/v1
kind: Deployment
metadata:
  name: customerapi
  labels:
    api: customerapi
spec:
  replicas: 2
  selector:
    matchLabels:
      api: customerapi
  template:
    metadata:
      labels:
        api: customerapi
    spec:
      containers:
      - image: msdemo/customerapi:1
        name: customerapi
        ports:
        - containerPort: 8080
