apiVersion: v1
kind: Service
metadata:
  labels:
    api: customerapi
  namespace: microservice-demo  
  name: customerapi
spec:
  ports:
  - nodePort: 30501
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    api: customerapi
  type: NodePort