apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderapi
  labels:
    api: orderapi
spec:
  replicas: 2
  selector:
    matchLabels:
      api: orderapi
  template:
    metadata:
      labels:
        api: orderapi
    spec:
      containers:
      - image: msdemo/orderapi:1
        name: orderapi
        ports:
        - containerPort: 8080
