apiVersion: v1
kind: Service
metadata:
  labels:
    api: orderapi
  name: orderapi
spec:
  ports:
  - nodePort: 30500
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    api: orderapi
  type: NodePort