apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu-quota
  namespace: microservice-demo
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "8"
    limits.memory: 6Gi